
name = "Gantt"
uuid = "1b08a953-4be3-4667-9a23-bb0ce80ae659"
authors = ["Thomas Fontana <thomas@fontana.onl>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
